---
channel: edge
addons:
  hassio-addon-jethub-mqtt-io:
    repository: jethome-ru/hassio-addon-jethub-mqtt-io
    target: hassio-addon-jethub-mqtt-io
    image: ghcr.io/jethome-ru/hassio-addon-jethub-mqtt-io/{arch}
