---
channel: edge
addons:
  addon-jethub-mqtt-io:
    repository: jethome-hassio-addons/addon-jethub-mqtt-io
    target: addon-jethub-mqtt-io
    image: ghcr.io/jethome-hassio-addons/addon-jethub-mqtt-io/{arch}
